name: "Run tests"

on:
  - push
  - pull_request

jobs:
  run-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: |
          uv sync --all-groups
          uv tool install tox --with tox-uv

      - name: Unit Tests
        run: |
          uv run tox -epy3
